#########################
## Client Information
#########################
client:
  name: Canary Promotion
  homepage: canarypromo.com

#########################
## Author Information
#########################
author:
  name: Mason Wendell
  email: mason@thecodingdesigner.com

#########################
## Style Prototype Settings
#########################

## General Prototype Settings
prototype:
  # If you would like a logo to appear in the banner, include its path here
  logo: false
  # If you would like to include webfonts, the following two provides have native support
  webfonts:
    # Typekit Kit ID (uses advanced loading method)
    typekit: false
    # Copy in the the families from inside the brackets [] from the JavaScript tab. Be sure to wrap it in "double quotes".
    googleFonts: false

## Main Navigation Sections
sections:
  Home: ''
  Style Tile: style-tile
  Elements: elements
  Typography: typography
  Components: components
  Colors: colors
  Canary: canary

## Style Tile Options
styleTile:
  # Number of possible colors
  colors: 3
  # Source links to inspirational images
  # Either relative paths from your images directory, or absolute paths to external images
  images:
    - http://fillmurray.com/960/540/
    - http://fillmurray.com/950/530/
    - http://fillmurray.com/940/520/
    - http://fillmurray.com/930/510/
    - http://fillmurray.com/920/500/
  # Descriptive keywords for Style Tile
  keywords:
    - Default
    - Minimal
    - Nothing
    - Design me!

#########################
## Component Guide
#########################
components:
  messages:
    - status
    - warning
    - error
  buttons:
    - Call to Action:
      - call-to-action
    - Big Button:
      - big-button
    - Warning Button:
      - big-button
      - red

#########################
## Color Guide
#########################
colors:
  # Variable names of the color variables being used
  variables:
    - black
    - orange
    - blue
  # The number of shades each color has
  shades: 6

#########################
## Server Options
#########################
server:
  port: 8000

#########################
## Export Options
#########################
export:
  path: export
  # If deploying somewhere (like GitHub Pages) where your files will not be located at the root directory, this will be the prefix that gets appended to assets run through image-url, style-url, script-url, and component-url
  assetPrefix: canary-neue

#########################
## Compass Options
#########################
compass:
  debugInfo: false
  # If you would like to add more Compass extensions, be sure to include the extensions in your Gemfile and re-run `bundle install`
  extensions:
    - style-prototypes
    - singularity-extras
    - survivalkit

#########################
## Versioning
#########################
bump:
  # Commit your files to Git after your bump
  commit: false
  # What files to commit. -a for all files
  files:
    - -a
  # Create a Git tag after your bump
  tag: false
  # Push changes to Git upstream after your bump
  push: false

#########################
## Git Options
#########################
git:
  # If you use grunt build --commit, this will be git commit message used
  defaultCommit: Production build and commit
  deployUpstream: origin
  deployBranch: gh-pages
